=== DeznekCZ/CharacterHandler/CharacterCreator/modules/DrD+2/database.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:db="database.xsd" elementFormDefault="unqualified">

  <xs:element name="module">
    <xs:complexType>
      <xs:choice>
        <xs:element name="stats" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="stats_group" minOccurs="0"
                maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="stat" minOccurs="0"
                      maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="sum" type="sumType" />
                            <xs:element name="value" type="valueType" />
                          </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="id" use="required"
                          type="xs:QName" />
                        <xs:attribute name="name" use="required"
                          type="xs:string" />
                        <xs:attribute name="visible" use="optional"
                          default="true" type="xs:boolean" />
                        <xs:attribute name="desc" use="required"
                          type="xs:string" />
                      </xs:complexType>
                      <xs:key name="ref">
                        <xs:selector xpath=".//db:stat" />
                        <xs:field xpath="@id" />
                      </xs:key>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" use="required"
                    type="xs:QName" />
                  <xs:attribute name="name" use="required"
                    type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="races" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="race" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="kind" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="bonus" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="ref" type="xs:QName" use="required"/>
                              <xs:attribute name="increase" type="xs:integer" use="required"/>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="skill" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="ref" type="xs:QName" use="required"/>
                              <xs:attribute name="lvl" type="xs:integer" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:QName"/>
                        <xs:attribute name="name" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:QName"/>
                  <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="skills" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="skill" minOccurs="0"
                maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="requirement">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="skill" type="skillType"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" use="required"
                    type="xs:QName" />
                  <xs:attribute name="name" use="required"
                    type="xs:string" />
                  <xs:attribute name="stat_enhance"
                    use="optional" type="xs:QName" />
                  <xs:attribute name="stat_use" use="optional"
                    type="xs:QName" />
                  <xs:attribute name="desc" use="required"
                    type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="weapons" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="weapon" minOccurs="0"
                maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="f2f" minOccurs="0"
                      maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" use="required"
                          type="xs:string" />
                        <xs:attribute name="skill" use="required"
                          type="xs:QName" />
                        <xs:attribute name="hand" use="required"
                          type="xs:string" />
                        <xs:attribute name="attack" use="required"
                          type="xs:integer" />
                        <xs:attribute name="slash_damage"
                          use="optional" type="xs:integer" />
                        <xs:attribute name="piercing_damage"
                          use="optional" type="xs:integer" />
                        <xs:attribute name="blunt_damage"
                          use="optional" type="xs:integer" />
                        <xs:attribute name="strength" use="required"
                          type="xs:integer" />
                        <xs:attribute name="length" use="required"
                          type="xs:integer" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ranged" minOccurs="0"
                      maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" use="required"
                          type="xs:string" />
                        <xs:attribute name="skill" use="required"
                          type="xs:QName" />
                        <xs:attribute name="hand" use="required"
                          type="xs:string" />
                        <xs:attribute name="attack" use="required"
                          type="xs:integer" />
                        <xs:attribute name="slash_damage"
                          use="optional" type="xs:integer" />
                        <xs:attribute name="piercing_damage"
                          use="optional" type="xs:integer" />
                        <xs:attribute name="blunt_damage"
                          use="optional" type="xs:integer" />
                        <xs:attribute name="strength" use="required"
                          type="xs:integer" />
                        <xs:attribute name="distance" use="required"
                          type="xs:integer" />
                        <xs:attribute name="strength_loading"
                          use="required" type="xs:integer" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="defense" minOccurs="0"
                      maxOccurs="1">
                      <xs:complexType>
                        <xs:attribute name="name" use="required"
                          type="xs:string" />
                        <xs:attribute name="skill" use="required"
                          type="xs:QName" />
                        <xs:attribute name="hand" use="required"
                          type="xs:string" />
                        <xs:attribute name="defense" use="required"
                          type="xs:integer" />
                        <xs:attribute name="strength" use="required"
                          type="xs:integer" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" use="required"
                    type="xs:QName" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="armors" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="armor" minOccurs="0"
                maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="id" use="required"
                    type="xs:QName" />
                  <xs:attribute name="name" use="required"
                    type="xs:string" />
                  <xs:attribute name="slash" use="required"
                    type="xs:integer" />
                  <xs:attribute name="piercing" use="required"
                    type="xs:integer" />
                  <xs:attribute name="blunt" use="required"
                    type="xs:integer" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="items" type="xs:string"></xs:element>
      </xs:choice>
      <xs:attribute name="id" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="sumType">
    <xs:complexContent>
      <xs:extension base="divableType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element name="sum" type="sumType" />
          <xs:element name="value" type="valueType"/>
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="divableType">
    <xs:attribute name="increment"  type="xs:integer" use="optional" />
    <xs:attribute name="divideUp"   type="xs:integer" use="optional" />
    <xs:attribute name="divideDown" type="xs:integer" use="optional" />
    <xs:attribute name="min"        type="xs:integer" use="optional" />
    <xs:attribute name="max"        type="xs:integer" use="optional" />
  </xs:complexType>

  <xs:complexType name="valueType">
    <xs:complexContent>
      <xs:extension base="divableType">
        <xs:attribute name="ref" type="xs:QName" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="skillType">
    <xs:attribute name="ref" type="xs:QName"/>
    <xs:attribute name="lvl" type="xs:integer"/>
  </xs:complexType>

</xs:schema>

=== DeznekCZ/CharacterHandler/CharacterCreator/modules/DrD+2/stats.xml
<?xml version="1.0" encoding="UTF-8"?>
<module id="drd+2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="database.xsd">
  <stats>
    <stats_group id="main" name="Hlavní vlastnosti">
      <stat id="sil" name="síla" desc="Vyjadřuje sílu hrdiny" />
      <stat id="obr" name="obratnost" desc="Vyjadřuje obratnost hrdiny" />
      <stat id="zrc" name="zručnost" desc="Vyjadřuje zručnost hrdiny" />
      <stat id="vol" name="vůle" desc="Vyjadřuje vůli hrdiny" />
      <stat id="int" name="inteligence" desc="Vyjadřuje inteligenci hrdiny" />
      <stat id="chr" name="charisma" desc="Vyjadřuje charismu hrdiny" />
    </stats_group>
    <stats_group id="ext" name="Odvozené vlastnosti">
      <stat id="odl" name="odolnost" desc="Vyjadřuje odolnost hrdiny vůči okolním vlivům (př. počasí)">
        <value ref="main.sil" />
      </stat>
      <stat id="kon" name="kondice"
        desc="Kondice vyjadřuje hrdinovu schonost vydržet vyšší silové či magické vypětí.">
        <sum increment="5">
          <value ref="main.odl" />
          <value ref="main.vol" />
        </sum>
      </stat>
      <stat id="moc" name="moc" desc="Vyjadřuje moc hrdiny\nPoužívá se pro určení síly kouzla.">
        <value ref="main.vol"/>
      </stat>
      <stat id="sms" name="smysly" desc="Smysly vyjadřují shopnost vnímat okolí">
        <value ref="main.zrc"/>
      </stat>
    </stats_group>
    <stats_group id="vzl" name="Vzhledové charakteristiky">
      <stat id="krs" name="krása" desc="">
        <sum>
          <sum divideUp="2">
            <value ref="main.obr"/>
            <value ref="main.zrc"/>
          </sum>
          <value ref="main.chr" divideUp="2"/>
        </sum>
      </stat>
      <stat id="dst" name="důstojnost" desc="">
        <sum>
          <sum divideUp="2">
            <value ref="main.int"/>
            <value ref="main.vol"/>
          </sum>
          <value ref="main.chr" divideUp="2"/>
        </sum>
      </stat>
      <stat id="neb" name="nebezpečnost" desc="">
        <sum>
          <sum divideUp="2">
            <value ref="main.sil"/>
            <value ref="main.vol"/>
          </sum>
          <value ref="main.chr" divideUp="2"/>
        </sum>
      </stat>
    </stats_group>
    <stats_group id="inc" name="Iniciativa">
      <stat id="f2f" name="útok z blízka" desc="">
        <value ref="main.obr"/>
      </stat>
      <stat id="ranged" name="střelba" desc="">
        <sum divideUp="2">
          <value ref="main.obr"/>
          <value ref="main.zrc"/>
        </sum>
      </stat>
      <stat id="magic" name="kouzlení" desc="">
        <sum divideUp="2">
          <value ref="main.obr"/>
          <value ref="main.int"/>
        </sum>
      </stat>
    </stats_group>
    <stats_group id="boj" name="Boj">
      <stat id="f2f" name="útok z blízka" desc="">
        <value ref="main.obr" divideDown="2"/>
      </stat>
      <stat id="ranged" name="střelba" desc="">
        <value ref="main.zrc" divideUp="2"/>
      </stat>
      <stat id="magic" name="kouzlení" desc="">
        <value ref="main.int"/>
      </stat>
      <stat id="def" name="obrana" desc="">
        <value ref="main.int" divideUp="2"/>
      </stat>
    </stats_group>
  </stats>
</module>
